@extends('executor.dashboard')

@section('content')
<div class="page-content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h4>Half-Yearly Reports</h4>
                    @if(in_array(auth()->user()->role, ['executor', 'applicant']))
                        <a href="{{ route('projects.index') }}" class="btn btn-primary">Generate New Half-Yearly Report</a>
                    @endif
                </div>
                <div class="card-body">
                    <form method="GET" action="{{ route('aggregated.half-yearly.index') }}" class="mb-4">
                        <div class="row">
                            <div class="col-md-3">
                                <select name="half_year" class="form-control">
                                    <option value="">All Half-Years</option>
                                    <option value="1" {{ request('half_year') == '1' ? 'selected' : '' }}>H1</option>
                                    <option value="2" {{ request('half_year') == '2' ? 'selected' : '' }}>H2</option>
                                </select>
                            </div>
                            <div class="col-md-3">
                                <input type="number" name="year" class="form-control" placeholder="Year" value="{{ request('year') }}" min="2020" max="{{ date('Y') }}">
                            </div>
                            <div class="col-md-3">
                                <button type="submit" class="btn btn-primary">Filter</button>
                                <a href="{{ route('aggregated.half-yearly.index') }}" class="btn btn-secondary">Clear</a>
                            </div>
                        </div>
                    </form>

                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Report ID</th>
                                    <th>Project</th>
                                    <th>Period</th>
                                    <th>Status</th>
                                    <th>Generated By</th>
                                    <th>AI Generated</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($reports as $report)
                                    <tr>
                                        <td>{{ $report->report_id }}</td>
                                        <td>{{ $report->project_title }}</td>
                                        <td>{{ $report->getPeriodLabel() }}</td>
                                        <td><span class="badge {{ $report->getStatusBadgeClass() }}">{{ $report->getStatusLabel() }}</span></td>
                                        <td>{{ $report->generatedBy->name ?? 'N/A' }}</td>
                                        <td>
                                            @if($report->aiInsights)
                                                <span class="badge bg-success">Yes</span>
                                            @else
                                                <span class="badge bg-secondary">No</span>
                                            @endif
                                        </td>
                                        <td>
                                            <a href="{{ route('aggregated.half-yearly.show', $report->report_id) }}" class="btn btn-sm btn-info">View</a>
                                            @if($report->isEditable() && $report->aiInsights)
                                                <a href="{{ route('aggregated.half-yearly.edit-ai', $report->report_id) }}" class="btn btn-sm btn-warning">Edit AI</a>
                                            @endif
                                        </td>
                                    </tr>
                                @empty
                                    <tr><td colspan="7" class="text-center">No half-yearly reports found.</td></tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                    {{ $reports->links() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
