    <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd;">
        <p><strong>Report Generated:</strong> {{ now()->format('d/m/Y H:i:s') }}</p>
        <p><strong>Generated By:</strong> {{ Auth::user()->name ?? 'System' }}</p>
    </div>
</body>
</html>
