@extends('executor.dashboard')

@section('content')
<div class="page-content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h4>Quarterly Reports</h4>
                    @if(in_array(auth()->user()->role, ['executor', 'applicant']))
                        <a href="{{ route('projects.index') }}" class="btn btn-primary">
                            Generate New Quarterly Report
                        </a>
                    @endif
                </div>
                <div class="card-body">
                    <!-- Filters -->
                    <form method="GET" action="{{ route('aggregated.quarterly.index') }}" class="mb-4">
                        <div class="row">
                            <div class="col-md-3">
                                <select name="quarter" class="form-control">
                                    <option value="">All Quarters</option>
                                    @foreach([1,2,3,4] as $q)
                                        <option value="{{ $q }}" {{ request('quarter') == $q ? 'selected' : '' }}>Q{{ $q }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="col-md-3">
                                <input type="number" name="year" class="form-control" placeholder="Year" value="{{ request('year') }}" min="2020" max="{{ date('Y') }}">
                            </div>
                            <div class="col-md-3">
                                <button type="submit" class="btn btn-primary">Filter</button>
                                <a href="{{ route('aggregated.quarterly.index') }}" class="btn btn-secondary">Clear</a>
                            </div>
                        </div>
                    </form>

                    <!-- Reports Table -->
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Report ID</th>
                                    <th>Project</th>
                                    <th>Period</th>
                                    <th>Status</th>
                                    <th>Generated By</th>
                                    <th>Generated At</th>
                                    <th>AI Generated</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($reports as $report)
                                    <tr>
                                        <td>{{ $report->report_id }}</td>
                                        <td>{{ $report->project_title }}</td>
                                        <td>{{ $report->getPeriodLabel() }}</td>
                                        <td>
                                            <span class="badge {{ $report->getStatusBadgeClass() }}">
                                                {{ $report->getStatusLabel() }}
                                            </span>
                                        </td>
                                        <td>{{ $report->generatedBy->name ?? 'N/A' }}</td>
                                        <td>{{ $report->generated_at ? $report->generated_at->format('d M Y') : 'N/A' }}</td>
                                        <td>
                                            @if($report->aiInsights)
                                                <span class="badge bg-success">Yes</span>
                                            @else
                                                <span class="badge bg-secondary">No</span>
                                            @endif
                                        </td>
                                        <td>
                                            <a href="{{ route('aggregated.quarterly.show', $report->report_id) }}" class="btn btn-sm btn-info">View</a>
                                            @if($report->isEditable() && $report->aiInsights)
                                                <a href="{{ route('aggregated.quarterly.edit-ai', $report->report_id) }}" class="btn btn-sm btn-warning">Edit AI</a>
                                            @endif
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="8" class="text-center">No quarterly reports found.</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>

                    {{ $reports->links() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
