@extends('executor.dashboard')

@section('content')
<div class="page-content">
    <div class="row">
        <div class="col-12">
            <!-- Basic Information -->
            <div class="card mb-3">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h4>Quarterly Report: {{ $report->getPeriodLabel() }}</h4>
                    <div>
                        @if($report->isEditable() && $report->aiInsights)
                            <a href="{{ route('aggregated.quarterly.edit-ai', $report->report_id) }}" class="btn btn-warning btn-sm">Edit AI Content</a>
                        @endif
                        <a href="{{ route('aggregated.quarterly.export-pdf', $report->report_id) }}" class="btn btn-secondary btn-sm">Export PDF</a>
                        <a href="{{ route('aggregated.quarterly.export-word', $report->report_id) }}" class="btn btn-secondary btn-sm">Export Word</a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="info-grid">
                        <div class="info-label"><strong>Report ID:</strong></div>
                        <div class="info-value">{{ $report->report_id }}</div>
                        <div class="info-label"><strong>Project:</strong></div>
                        <div class="info-value">{{ $report->project_title }}</div>
                        <div class="info-label"><strong>Period:</strong></div>
                        <div class="info-value">{{ $report->period_from->format('d M Y') }} - {{ $report->period_to->format('d M Y') }}</div>
                        <div class="info-label"><strong>Status:</strong></div>
                        <div class="info-value">
                            <span class="badge {{ $report->getStatusBadgeClass() }}">{{ $report->getStatusLabel() }}</span>
                        </div>
                        <div class="info-label"><strong>Generated By:</strong></div>
                        <div class="info-value">{{ $report->generatedBy->name ?? 'N/A' }}</div>
                        <div class="info-label"><strong>Generated At:</strong></div>
                        <div class="info-value">{{ $report->generated_at ? $report->generated_at->format('d M Y H:i') : 'N/A' }}</div>
                        <div class="info-label"><strong>Total Beneficiaries:</strong></div>
                        <div class="info-value">{{ $report->total_beneficiaries ?? 'N/A' }}</div>
                    </div>
                </div>
            </div>

            <!-- AI Title -->
            @if($report->aiTitle)
                <div class="card mb-3">
                    <div class="card-header">
                        <h4>{{ $report->aiTitle->report_title ?? 'Quarterly Progress Report' }}</h4>
                    </div>
                </div>
            @endif

            <!-- AI Insights -->
            @if($report->aiInsights)
                <!-- Executive Summary -->
                @if($report->aiInsights->executive_summary)
                    <div class="card mb-3">
                        <div class="card-header">
                            <h5>{{ $report->aiTitle->getSectionHeading('executive_summary', 'Executive Summary') ?? 'Executive Summary' }}</h5>
                        </div>
                        <div class="card-body">
                            <p>{!! nl2br(e($report->aiInsights->executive_summary)) !!}</p>
                        </div>
                    </div>
                @endif

                <!-- Key Achievements -->
                @if($report->aiInsights->key_achievements && count($report->aiInsights->key_achievements) > 0)
                    <div class="card mb-3">
                        <div class="card-header">
                            <h5>{{ $report->aiTitle->getSectionHeading('key_achievements', 'Key Achievements') ?? 'Key Achievements' }}</h5>
                        </div>
                        <div class="card-body">
                            <ul>
                                @foreach($report->aiInsights->key_achievements as $achievement)
                                    <li>
                                        @if(is_array($achievement))
                                            <strong>{{ $achievement['title'] ?? 'Achievement' }}:</strong> {{ $achievement['description'] ?? '' }}
                                        @else
                                            {{ $achievement }}
                                        @endif
                                    </li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                @endif

                <!-- Progress Trends -->
                @if($report->aiInsights->progress_trends)
                    <div class="card mb-3">
                        <div class="card-header">
                            <h5>{{ $report->aiTitle->getSectionHeading('progress_trends', 'Progress Trends') ?? 'Progress Trends' }}</h5>
                        </div>
                        <div class="card-body">
                            @if(is_array($report->aiInsights->progress_trends))
                                @foreach($report->aiInsights->progress_trends as $key => $trend)
                                    <div class="mb-3">
                                        <strong>{{ ucfirst(str_replace('_', ' ', $key)) }}:</strong>
                                        @if(is_array($trend))
                                            <p>{{ $trend['description'] ?? '' }}</p>
                                        @else
                                            <p>{{ $trend }}</p>
                                        @endif
                                    </div>
                                @endforeach
                            @else
                                <p>{{ $report->aiInsights->progress_trends }}</p>
                            @endif
                        </div>
                    </div>
                @endif

                <!-- Challenges -->
                @if($report->aiInsights->challenges && count($report->aiInsights->challenges) > 0)
                    <div class="card mb-3">
                        <div class="card-header">
                            <h5>{{ $report->aiTitle->getSectionHeading('challenges', 'Challenges') ?? 'Challenges' }}</h5>
                        </div>
                        <div class="card-body">
                            <ul>
                                @foreach($report->aiInsights->challenges as $challenge)
                                    <li>
                                        @if(is_array($challenge))
                                            <strong>{{ $challenge['challenge'] ?? 'Challenge' }}:</strong> {{ $challenge['description'] ?? '' }}
                                        @else
                                            {{ $challenge }}
                                        @endif
                                    </li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                @endif

                <!-- Recommendations -->
                @if($report->aiInsights->recommendations && count($report->aiInsights->recommendations) > 0)
                    <div class="card mb-3">
                        <div class="card-header">
                            <h5>{{ $report->aiTitle->getSectionHeading('recommendations', 'Recommendations') ?? 'Recommendations' }}</h5>
                        </div>
                        <div class="card-body">
                            <ul>
                                @foreach($report->aiInsights->recommendations as $recommendation)
                                    <li>
                                        @if(is_array($recommendation))
                                            <strong>{{ $recommendation['recommendation'] ?? 'Recommendation' }}:</strong>
                                            {{ $recommendation['rationale'] ?? '' }}
                                            @if(isset($recommendation['priority']))
                                                <span class="badge bg-{{ $recommendation['priority'] == 'high' ? 'danger' : ($recommendation['priority'] == 'medium' ? 'warning' : 'info') }}">
                                                    {{ ucfirst($recommendation['priority']) }} Priority
                                                </span>
                                            @endif
                                        @else
                                            {{ $recommendation }}
                                        @endif
                                    </li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                @endif
            @else
                <div class="alert alert-info">
                    <p>No AI insights available for this report. <a href="{{ route('aggregated.quarterly.edit-ai', $report->report_id) }}">Generate AI insights</a></p>
                </div>
            @endif

            <!-- Objectives -->
            @if($report->objectives->isNotEmpty())
                <div class="card mb-3">
                    <div class="card-header">
                        <h4>Objectives</h4>
                    </div>
                    <div class="card-body">
                        @foreach($report->objectives as $objective)
                            <div class="mb-3">
                                <h6>{{ $objective->objective_text }}</h6>
                                @if($objective->cumulative_progress)
                                    <p><strong>Progress:</strong> {{ $objective->cumulative_progress }}</p>
                                @endif
                            </div>
                        @endforeach
                    </div>
                </div>
            @endif

            <!-- Budget Details -->
            @if($report->details->isNotEmpty())
                <div class="card mb-3">
                    <div class="card-header">
                        <h4>Budget Details</h4>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>Particulars</th>
                                        <th>Opening Balance</th>
                                        <th>Amount Forwarded</th>
                                        <th>Amount Sanctioned</th>
                                        <th>Total Amount</th>
                                        <th>Total Expenses</th>
                                        <th>Closing Balance</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($report->details as $detail)
                                        <tr>
                                            <td>{{ $detail->particulars }}</td>
                                            <td>{{ format_indian($detail->opening_balance, 2) }}</td>
                                            <td>{{ format_indian($detail->amount_forwarded, 2) }}</td>
                                            <td>{{ format_indian($detail->amount_sanctioned, 2) }}</td>
                                            <td>{{ format_indian($detail->total_amount, 2) }}</td>
                                            <td>{{ format_indian($detail->total_expenses, 2) }}</td>
                                            <td>{{ format_indian($detail->closing_balance, 2) }}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            @endif

            <!-- Photos -->
            @if($report->photos->isNotEmpty())
                <div class="card mb-3">
                    <div class="card-header">
                        <h4>Photos</h4>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            @foreach($report->photos as $photo)
                                <div class="col-md-3 mb-3">
                                    <img src="{{ asset('storage/' . $photo->photo_path) }}" alt="Photo" class="img-fluid">
                                    @if($photo->description)
                                        <p class="mt-2"><small>{{ $photo->description }}</small></p>
                                    @endif
                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>
            @endif

            <div class="mt-3">
                <a href="{{ route('aggregated.quarterly.index') }}" class="btn btn-secondary">Back to List</a>
            </div>
        </div>
    </div>
</div>
@endsection

<style>
.info-grid {
    display: grid;
    grid-template-columns: 20% 80%;
    grid-gap: 20px;
    align-items: start;
}

.info-label {
    font-weight: bold;
    margin-right: 10px;
    word-wrap: break-word;
    overflow-wrap: break-word;
    word-break: break-word;
    white-space: normal;
}

.info-value {
    word-wrap: break-word;
    overflow-wrap: break-word;
    word-break: break-word;
    white-space: normal;
    padding-left: 10px;
}

@media (max-width: 768px) {
    .info-grid {
        grid-template-columns: 1fr;
        grid-gap: 10px;
    }

    .info-label {
        margin-right: 0;
        margin-bottom: 5px;
    }

    .info-value {
        padding-left: 0;
    }
}
</style>

<script src="{{ asset('js/report-view-hide-empty.js') }}"></script>
@endsection
